# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20190627_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoCode',
            new_name='CodeAnnotation',
        ),
        migrations.RenameModel(
            old_name='InfoPage',
            new_name='PageAnnotation',
        ),
        migrations.RenameModel(
            old_name='InfoVideo',
            new_name='VideoAnnotation',
        ),
    ]
