# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20190628_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='textfolder',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
