# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_pdf_textfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPDFAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField()),
                ('pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.PDF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkVideoAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField()),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.PDF')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
