# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_auto_20190630_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineOfCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNumber', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='codeannotation',
            name='camino',
        ),
        migrations.RemoveField(
            model_name='codeannotation',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='codeannotation',
            name='line',
        ),
        migrations.RemoveField(
            model_name='codeannotation',
            name='pagerank',
        ),
        migrations.AddField(
            model_name='lineofcode',
            name='codeAnnotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.CodeAnnotation'),
        ),
    ]
