# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_codeannotation_sequencerank'),
    ]

    operations = [
        migrations.CreateModel(
            name='mappedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='videoannotation',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='videoannotation',
            name='pagerank',
        ),
        migrations.RemoveField(
            model_name='videoannotation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='videoannotation',
            name='URI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timestamp',
            name='videoAnnotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.VideoAnnotation'),
        ),
        migrations.AddField(
            model_name='mappedwords',
            name='videoAnnotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.VideoAnnotation'),
        ),
    ]
