# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0011_auto_20190712_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='timestampFile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcriptionFile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
