# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0013_auto_20190713_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoannotation',
            name='camino',
        ),
        migrations.AddField(
            model_name='videoannotation',
            name='wikilink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
